### ISSUE TITLE
Pour les services publiés, proposer des options

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr#253]
A compléter : 
- [ ] ~~autoriser publication dans le catalogue (hors bac à sable). défaut = Oui (lieu de stockage de l'information ?)~~
- [x]  autoriser l'utilisation dans l'entrée cartographique. Défaut = Oui (lieu de stockage de l'information ?) ~~#475~~ #564 
- [ ] autoriser le signalement sur la donnée (réalisé depuis l'entrée cartographique)  (si oui au bullet précédent) (lieu de stockage de l'information ?) https://github.com/IGNF/cartes.gouv.fr/issues/476
- [ ] autoriser l'utilisation dans les guichets : à tous, à sa communauté, à des communautés ou utilisateurs choisis (lieu de stockage de l'information ?) https://github.com/IGNF/cartes.gouv.fr/issues/477
- [ ] autoriser l'utilisation dans cartoviz : à tous, à sa communauté, à des communautés ou utilisateurs choisis (lieu de stockage de l'information ?)

**Comment by IGNF-Xavier** [comment]
Explication du changement de milestone : découpage en plusieurs tickets pour répondre à remarque @elias75015
